command:
  - sh
  - -c
  - npm install --production && node server.js

env:
  - name: NODE_ENV
    value: "production"
  - name: PROMETHEUX_AUTH_URL
    value: "https://auth.prometheux.ai/functions/v1"
