command:
  - sh
  - -c
  - npm install --production && node server.js

env:
  - name: NODE_ENV
    value: "production"
  - name: SUPABASE_FUNCTIONS_URL
    value: "https://bzvynvfsaqzzqndbylhk.supabase.co/functions/v1"
